name: BSDs
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_bsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          # https://github.com/vmactions/freebsd-vm/issues/71
          mkdir -p /usr/local/etc/pkg/repos
          echo "FreeBSD: { url: "pkg+http://pkg.freebsd.org/\${ABI}/latest" }" > /usr/local/etc/pkg/repos/FreeBSD.conf
          pkg update -f

          pkg install -y \
            bash \
            boost-libs \
            cmake git \
            llvm19 \
            ninja \
            qt6-base qt6-declarative qt6-shadertools qt6-websockets qt6-serialport qt6-scxml qt6-imageformats \
            ffmpeg \
            lilv suil lv2 \
            libcoap \
            portaudio \
            pd \
            libfmt spdlog \
            rubberband libsamplerate libsndfile \
            libcoap \
            freetype2 harfbuzz fontconfig \
            alsa-lib jackit

        run: |
          ./ci/common.deps.sh
          ./ci/freebsd.build.sh
