name: Linux distro build
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fedora:
    name: Fedora (latest)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Install git
        run: |
          dnf -y install git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/fedora.deps.sh

      - name: Build
        run: |
          ./ci/fedora.build.sh

#  suseleap:
#    name: OpenSUSE Leap
#    runs-on: ubuntu-latest
#    container:
#      image: opensuse/leap:latest
#
#    steps:
#      - name: Install git
#        run: |
#          zypper -n install git
#
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          submodules: 'recursive'
#
#      - name: Dependencies
#        run: |
#          ./ci/suse.leap.deps.sh
#
#      - name: Build
#        run: |
#          ./ci/suse.build.sh

  susetumbleweed:
    name: OpenSUSE Tumbleweed
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
      options: --privileged

    steps:
      - name: Install git
        run: |
          zypper -n install git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/suse.tumbleweed.deps.sh

      - name: Build
        run: |
          ./ci/suse.build.sh

  archqt6:
    name: ArchLinux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install git
        run: |
          pacman -Syy --noconfirm
          pacman -S glibc --noconfirm
          pacman -S git --noconfirm

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/archlinux.deps.sh

      - name: Build
        run: |
          ./ci/archlinux.build.sh


  archqt6system:
    name: ArchLinux (System)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install git
        run: |
          pacman -Syy --noconfirm
          pacman -S glibc --noconfirm
          pacman -S git --noconfirm

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/archlinux.system.deps.sh

      - name: Build
        run: |
          ./ci/archlinux.system.build.sh
