name: Tarball
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tarball:
    name: Tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Continuous tag
        uses: rickstaa/action-create-tag@v1
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }} && github.event_name != 'pull_request'
        with:
          tag: "continuous"
          tag_exists_error: false
          message: "Continuous build"
          force_push_tag: true

      - name: Build
        run: |
          export GITTAGNOV=$(echo "$GITHUB_REF" | sed "s/.*\///;s/^v//")
          ./ci/tarball.build.sh
        env:
          GPG_SIGN_PUBKEY: ${{ secrets.GPG_SIGN_PUBKEY }}
          GPG_SIGN_PRIVKEY: ${{ secrets.GPG_SIGN_PRIVKEY }}

      - name: Deploy
        run: |
          export GITTAGNOV=$(echo "$GITHUB_REF" | sed "s/.*\///;s/^v//")
          export BUILD_ARTIFACTSTAGINGDIRECTORY="$PWD/staging"
          mkdir -p "$BUILD_ARTIFACTSTAGINGDIRECTORY"
          ./ci/tarball.deploy.sh

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: |
            staging/*.*

      - name: Continuous
        uses: softprops/action-gh-release@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }} && github.event_name != 'pull_request'
        with:
          name: "Continuous"
          tag_name: "continuous"
          body: ""
          append_body: true
          generate_release_notes: true
          files: |
            staging/*.*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        with:
          body: ""
          append_body: true
          generate_release_notes: true
          files: |
            staging/*.*
