name: Ubuntu build
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { deploy: false, distro: ubuntu.jammy,  image: jammy,  CC: /opt/gcc-14/bin/gcc, CXX: /opt/gcc-14/bin/g++, CFLAGS: "-O0", LDFLAGS: "" }
          - { deploy: true,  distro: ubuntu.jammy,  image: jammy,  CC: clang-20,            CXX: clang++-20,          CFLAGS: "-O3", LDFLAGS: "-fuse-ld=lld-20" }
          - { deploy: false, distro: ubuntu.noble,  image: noble,  CC: gcc-14,              CXX: g++-14,              CFLAGS: "-O0", LDFLAGS: "-fuse-ld=lld" }
          - { deploy: true,  distro: ubuntu.noble,  image: noble,  CC: clang-19,            CXX: clang++-19,          CFLAGS: "-O3", LDFLAGS: "-fuse-ld=lld-19" }
          - { deploy: false, distro: ubuntu.plucky, image: plucky, CC: gcc,                 CXX: g++,                 CFLAGS: "-O0", LDFLAGS: "-fuse-ld=lld" }
          - { deploy: true,  distro: ubuntu.plucky, image: plucky, CC: clang-20,            CXX: clang++-20,          CFLAGS: "-O3", LDFLAGS: "-fuse-ld=lld-20" }

    container:
      image: ubuntu:${{ matrix.image }}

    steps:
      - name: Install git
        run: |
          apt-get update -qq
          apt-get install -qq --force-yes git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/${{ matrix.distro }}.deps.sh

      - name: Build
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
          CFLAGS: ${{ matrix.CFLAGS }}
          LDFLAGS: ${{ matrix.LDFLAGS }}
        run: |
          ./ci/${{ matrix.distro }}.build.sh

      - name: Deploy
        run: |
          ./ci/${{ matrix.distro }}.deploy.sh

      - name: Upload build
        uses: actions/upload-artifact@v4
        if: matrix.deploy
        with:
          name: ${{ matrix.distro }}-amd64
          path: |
            *.deb

      - name: Continuous
        uses: softprops/action-gh-release@v2
        if: matrix.deploy && ${{ ! startsWith(github.ref, 'refs/tags/') }} && github.event_name != 'pull_request'
        with:
          name: "Continuous"
          tag_name: "continuous"
          body: ""
          append_body: true
          generate_release_notes: false
          files: |
            *.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        if: matrix.deploy && startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        with:
          body: ""
          append_body: true
          generate_release_notes: false
          files: |
            *.deb
